Fgalar
fgalar/Corewar pull request #5
Opened 2020-09-18 17:30 UTC by fgalar

2020-09-18 19:44 UTC, AndreIglesias commented on assembler/include/asm.h
> +int					translate(t_file *file, char *file_name);
- Le nom du fichier est déjà dans la structure **file**.
- La variable **verbosity** (necesaire pour le bonus) a été supprimé.
   - Cela sert pour imprimer la table de syntaxe avant de commencer la traduction.

2020-09-18 19:52 UTC, AndreIglesias commented on assembler/src/asm_main.c
> +			translate(&file, av[2]);
- Le nom du fichier est déjà dans la structure **file**.
- La variable **verbosity** (necesaire pour le bonus) n'a pas été envoyé à la fonction _translate_.
   - Cela sert pour imprimer la table de syntaxe avant de commencer la traduction.
- La fonction **translate** doit s'executer avec ou sans la flag de _verbosity_ (-v)

2020-09-18 19:59 UTC, AndreIglesias commented on assembler/src/synthesis/translation.c
> +}
tu ne préfères pas ft_printf_fd qui est dans ma libft? xD

2020-09-18 19:59 UTC, AndreIglesias commented on assembler/src/synthesis/translation.c
> +}
tu ne préfères pas ft_printf_fd (il est dans ma libft)? xD

2020-09-18 20:01 UTC, AndreIglesias commented on assembler/src/synthesis/translation.c
> -		}
verbosity est pour imprimer la table

2020-09-18 20:03 UTC, AndreIglesias requested changes
- Le nom du fichier est déjà dans la structure **file** (pas besoin de l'envoyer a nouveau).
- La variable **verbosity** (necesaire pour le bonus) a été supprimé.
   - Cela sert pour imprimer la table de syntaxe avant de commencer la traduction.
- La fonction **translate** doit s'executer avec ou sans la flag de _verbosity_ (-v)

2020-09-21 10:34 UTC, Jehutyi approved these changes

2020-09-30 16:03 UTC, merged